// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JlionOrderService.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Jlion.NetCore.OrderService.Service.Grpc {
  public static partial class JlionOrderService
  {
    static readonly string __ServiceName = "Jlion.NetCore.OrderService.Service.Grpc.JlionOrderService";

    static readonly grpc::Marshaller<global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchRequest> __Marshaller_OrderSearchRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchResponse> __Marshaller_OrderSearchResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchRequest, global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchResponse> __Method_Order_Search = new grpc::Method<global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchRequest, global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Order_Search",
        __Marshaller_OrderSearchRequest,
        __Marshaller_OrderSearchResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Jlion.NetCore.OrderService.Service.Grpc.JlionOrderServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of JlionOrderService</summary>
    public abstract partial class JlionOrderServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchResponse> Order_Search(global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for JlionOrderService</summary>
    public partial class JlionOrderServiceClient : grpc::ClientBase<JlionOrderServiceClient>
    {
      /// <summary>Creates a new client for JlionOrderService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public JlionOrderServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for JlionOrderService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public JlionOrderServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected JlionOrderServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected JlionOrderServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchResponse Order_Search(global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Order_Search(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchResponse Order_Search(global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Order_Search, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchResponse> Order_SearchAsync(global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Order_SearchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchResponse> Order_SearchAsync(global::Jlion.NetCore.OrderService.Service.Grpc.OrderSearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Order_Search, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override JlionOrderServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new JlionOrderServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(JlionOrderServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Order_Search, serviceImpl.Order_Search).Build();
    }

  }
}
#endregion
