// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JlionOrderService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Jlion.NetCore.OrderService.Service.Grpc {

  /// <summary>Holder for reflection information generated from JlionOrderService.proto</summary>
  public static partial class JlionOrderServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for JlionOrderService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static JlionOrderServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdKbGlvbk9yZGVyU2VydmljZS5wcm90bxInSmxpb24uTmV0Q29yZS5PcmRl",
            "clNlcnZpY2UuU2VydmljZS5HcnBjGhJPcmRlclJlcXVlc3QucHJvdG8yoQEK",
            "EUpsaW9uT3JkZXJTZXJ2aWNlEosBCgxPcmRlcl9TZWFyY2gSOy5KbGlvbi5O",
            "ZXRDb3JlLk9yZGVyU2VydmljZS5TZXJ2aWNlLkdycGMuT3JkZXJTZWFyY2hS",
            "ZXF1ZXN0GjwuSmxpb24uTmV0Q29yZS5PcmRlclNlcnZpY2UuU2VydmljZS5H",
            "cnBjLk9yZGVyU2VhcmNoUmVzcG9uc2UiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Jlion.NetCore.OrderService.Service.Grpc.OrderRequestReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
